language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -e .
  - pip install coveralls
script: coverage run --source=pubmed_lookup setup.py test
after_success: coveralls
